### ISSUE TITLE
Can BakingTray be used for two photon microscopy? 

### ISSUE THREAD

**Issue by hwuscut** [SainsburyWellcomeCentre/BakingTray#165]
Excuse me, can BakingTray be used for two photon microscopy?  How can I modify the codes?

**Comment by raacampbell** [comment]
I suspect you want to use [http://scanimage.vidriotechnologies.com/display/SI2017/Supported+Microscope+Hardware](ScanImage). BakingTray, is a ScanImage wrapper that performs serial-section 2-photon tomography

**Comment by hwuscut** [comment]
Thanks so much.
