### ISSUE TITLE
Is there a hard max limit on image size in preview window?

### ISSUE THREAD

**Issue by raacampbell** [SainsburyWellcomeCentre/BakingTray#188]
@ablot  says:

"I don't manage to extend my preview scan towards the right but I  don't get error messages. Ah found it... _y_ cannot be more than 20"

**Comment by ablot** [comment]
To be more precise, if I manually enter a number above 20 for the Y size, it get reduced to 20 when I click somewhere else

**Comment by raacampbell** [comment]
Fixed: f206756821d4ab94fb227466cea5fed85ad1793c
