### ISSUE TITLE
Lauching acquisition with Average Factor not set to 1

### ISSUE THREAD

**Issue by HugoB** [SainsburyWellcomeCentre/BakingTray#314]
Hello Rob, 

I am trying to launch an acquisition while averaging each frame 5 or 10 times. I tried with big stacks of around 70 z plans but the cache memory exploded and Matlab crashed (64 Gb full).
So I tried with fewer plans (6) but know the matlab console is spamming : "ERROR in everyNEvent callback of Task object: Index exceeds array bounds."

Is there a workaround to do an acquisition while averaging the frames ?

**Comment by raacampbell** [comment]
For linear scanning do not average frames. Change your scan settings so that the line period and dwell time increase. e.g. increase the number of samples per pixel.

**Comment by HugoB** [comment]
Ok !
Thank you.

**Comment by raacampbell** [comment]
This is now mentioned on this documentation page: https://bakingtray.mouse.vision/users/choosing-resolution
