### ISSUE TITLE
Overlap Z planes not coming back to 0

### ISSUE THREAD

**Issue by HugoB** [SainsburyWellcomeCentre/BakingTray#357]
Hello Rob, 

By using the new GUI and editing the "# Overlap Z planes" field in main BT gui, I can't put the value back to 0 if I previously changed it. However I can initialize BT with 0 overlapping z planes. 
Same thing with the command line hBT.recipe.mosaic.numOverlapZPlanes=0; so probably not gui related bug...

Best, 
Hugo

**Comment by raacampbell** [comment]
Hmmm... Weird. I'll check it out. We never used that setting so it's quite possible I'd miss something like this.

**Comment by raacampbell** [comment]
Fixed 46a61ceb5f83b8798c86d068eb19283c1041e89d 
That's in `dev`; I'll merge into `master` with a bunch of other fixes later today.
